### ISSUE TITLE
Residue number in PDB > 9999

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#98]
By testing a POPC / POPE system (https://zenodo.org/record/1402449), I got the following error:

```
$ buildH -c start.gro -l Berger_POPC -d Berger_POPC.def -t md_dt100_OK_centered.xtc -opx OUT_POPC -o OP_POPC.dat
[...]
Constructing the system...
System has 46600 atoms
Writing new pdb with hydrogens.
Traceback (most recent call last):
  File "/home/fuchs/miniconda3/envs/buildh/bin/buildH", line 33, in <module>
    sys.exit(load_entry_point('buildh', 'console_scripts', 'buildH')())
  File "/home/fuchs/papers/buildH_project/buildH/buildh/UI.py", line 146, in entry_point
    main(args.coord, args.traj, args.defop, args.out, args.opdbxtc, dic_lipid, args.begin, args.end)
  File "/home/fuchs/papers/buildH_project/buildH/buildh/UI.py", line 328, in main
    core.gen_coordinates_calcOP(prefix_traj_ouput, universe_woH, dic_OP, dic_lipid,
  File "/home/fuchs/papers/buildH_project/buildH/buildh/core.py", line 619, in gen_coordinates_calcOP
    universe_wH = mda.Universe(pdbout_filename)
  File "/home/fuchs/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 389, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/home/fuchs/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 582, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/home/fuchs/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py", line 341, in __init__
    self._read_frame(0)
  File "/home/fuchs/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py", line 451, in _read_frame
    self.ts.positions = tmp_buf
  File "/home/fuchs/miniconda3/envs/buildh/lib/python3.9/site-packages/MDAnalysis/coordinates/base.py", line 645, in positions
    self._pos[:] = new
ValueError: could not convert string to float: '0  78.18'
```

The pb is here in the generated pdb (with hydrogens) when the residue number gets over 9999:

```
[...]
ATOM  53035  OW   SOL 9999      60.690  18.620  12.500  1.00  0.00             O
ATOM  53036  HW1  SOL 9999      61.010  19.020  13.360  1.00  0.00             H
ATOM  53037  HW2  SOL 9999      60.010  17.910  12.700  1.00  0.00             H
ATOM  53038  OW   SOL 10000      91.160  78.180  20.140  1.00  0.00             O
ATOM  53039  HW1  SOL 10000      92.110  78.400  19.920  1.00  0.00             H
[...]
```

I think we need to reset this number to 1 or 0 when it exceeds 9999. For info, GROMACS resets it to 0.

**Comment by patrickfuchs** [comment]
Above, I gave a gro file as input. Even if I give a pdb which has the resnum reset to 0:

```
[...]
ATOM  42539  OW  SOL  9999      60.690  18.620  12.500  1.00  0.00
ATOM  42540  HW1 SOL  9999      61.010  19.020  13.360  1.00  0.00
ATOM  42541  HW2 SOL  9999      60.010  17.910  12.700  1.00  0.00
ATOM  42542  OW  SOL     0      91.160  78.180  20.140  1.00  0.00
ATOM  42543  HW1 SOL     0      92.110  78.400  19.920  1.00  0.00
ATOM  42544  HW2 SOL     0      90.790  77.580  19.430  1.00  0.00
[...]
```
MDAnalysis ignores the PDB resnum and uses its own (by doing a print I get this):

```
[...]
<Atom 42539: OW of type O of resname SOL, resid 9999 and segid SYSTEM and altLoc >
<Atom 42540: HW1 of type H of resname SOL, resid 9999 and segid SYSTEM and altLoc >
<Atom 42541: HW2 of type H of resname SOL, resid 9999 and segid SYSTEM and altLoc >
<Atom 42542: OW of type O of resname SOL, resid 10000 and segid SYSTEM and altLoc >
<Atom 42543: HW1 of type H of resname SOL, resid 10000 and segid SYSTEM and altLoc >
<Atom 42544: HW2 of type H of resname SOL, resid 10000 and segid SYSTEM and altLoc >
[...]
```
So we have to reset the resnum ourselves in `core.py`: https://github.com/patrickfuchs/buildH/blob/3ef6ae022761abaa1d04b36546412911b721dfba/buildh/core.py#L106
